### ISSUE TITLE
Missing "date.h"

### ISSUE THREAD

**Issue by MarkGannon** [Bill-Gray/jpl_eph#2]
I checked out jpl_eph, but when I try and compile the code, I get an error message about note being able to find "date.h".  The output looks like:

> g++ -Wall -O3 -Wextra -pedantic -I ~/include -c asc2eph.cpp
> g++ -Wall -O3 -Wextra -pedantic -I ~/include -c f_strtod.cpp
> g++ -o asc2eph asc2eph.o f_strtod.o 
> g++ -Wall -O3 -Wextra -pedantic -I ~/include -c dump_eph.cpp
> g++ -Wall -O3 -Wextra -pedantic -I ~/include -c jpleph.cpp
> rm libjpl.a
> rm: cannot remove 'libjpl.a': No such file or directory
> make: [makefile:54: libjpl.a] Error 1 (ignored)
> ar rv libjpl.a jpleph.o
> ar: creating libjpl.a
> a - jpleph.o
> g++ -o dump_eph dump_eph.o libjpl.a 
> g++ -Wall -O3 -Wextra -pedantic -I ~/include -c eph2asc.cpp
> g++ -o eph2asc eph2asc.o libjpl.a 
> g++ -Wall -O3 -Wextra -pedantic -I ~/include -c ftest.cpp
> g++ -o ftest ftest.o f_strtod.o
> g++ -Wall -O3 -Wextra -pedantic -I ~/include -c merge_de.cpp
> g++ -o merge_de merge_de.o libjpl.a 
> g++ -Wall -O3 -Wextra -pedantic -I ~/include -c testeph.cpp
> g++ -o testeph testeph.o libjpl.a 
> g++ -Wall -O3 -Wextra -pedantic -I ~/include -c -DTEST_MAIN sub_eph.cpp
> sub_eph.cpp:28:18: fatal error: date.h: No such file or directory
>  #include "date.h"
>                   ^
> compilation terminated.
> make: *** [makefile:79: sub_eph.o] Error 1

Some Googleing resulted in a likely date.h candidate at: 
[U of Washington](http://faculty.washington.edu/tlumley/calendars/) .  It isn't entirely clear if that is the appropriate one to include or not.

Thanks in advance for your help.

**Comment by Bill-Gray** [comment]
I've just pushed a revised `makefile` that corrects this.  However,  unless you're going to use `sub_eph` (almost no one does),  you can safely ignore this.

The problem is that `sub_eph` depends on the `lunar` library (see https://github.com/Bill-Gray/lunar ).  That library contains basic astronomical functions,  including date/time code.  Good stuff,  but the only place it's used in the `jpl_eph` code is in `sub_eph`.

So the revised `makefile` just doesn't include `sub_eph` in the list of utilities built by default.  You can run `make sub_eph` if you actually want it.  Which,  as stated above,  almost no one really does.

**Comment by Bill-Gray** [comment]
Should perhaps have mentioned:  the U of Washington `date.cpp`,  `date.c`,  and `watdefs.h`  are older versions of the `lunar` code.  Quite a bit older,  in fact... use the newer code at https://github.com/Bill-Gray/lunar .

**Comment by MarkGannon** [comment]
That did fixed the compile issue.  Thanks for the quick response and for making your code available!
