### ISSUE TITLE
Assertion error in jpleph.cpp

### ISSUE THREAD

**Issue by dekishalay** [Bill-Gray/jpl_eph#6]
Hello! 

We've been using this code together with integrat and astcheck (https://www.projectpluto.com/astcheck.htm) to cross-match detected transients to known solar system bodies. As of a few weeks ago, the jpleph.cpp routine started throwing this error:

integrat: jpleph.cpp:328: void interp(interpolation_info*, const double*, const double*, unsigned int, unsigned int, unsigned int, int, double*): Assertion `tc >= -1.' failed.

We're trying to figure out what causes this but don't have a fix yet. Is this a known issue that has a fix?

Thanks for your help,
Kishalay.

**Comment by Bill-Gray** [comment]
Hi Kishalay,

   This sounds quite a bit like a problem that was reported to me back in December.  It turned out that I'd made some embarrassing mistakes in the code.  I fixed those,  the gent reporting the problem pulled the changes,  rebuilt,  reinstalled,  and it all worked again.

   I would recommend that you do a 'git pull',  'make',  'make install' for the `jpl_eph` repository.  Then in the `lunar` repository,  run 'git pull',  'make',  'make integrat',  and 'make install_integrat'.  Do that,  and I expect all will work correctly.

The odd make sequence is because Integrat is not built by default.  Most people are (I am reasonably sure) only using other bits of the `lunar` repository;  I wanted them to be able to build everything they actually wanted without having to bring in the `jpl_eph` dependency that Integrat has.  It _is_ a strange sequence... but run that,  and Integrat should be re-built,  this time with the fix to my silly mistakes... let me know if you're still seeing problems.

--Bill

**Comment by dekishalay** [comment]
Hi Bill,

Thanks, pulling and reinstalling the code did fix the issue!

Regards
Kishalay

**Comment by Bill-Gray** [comment]
My favorite kind of bug : one that I've already fixed... thanks for confirming it's working.
